#!/usr/bin/env python3
"""Build the whole-domain energy-partition table (reviewer energy-accounting ask).

At steady state Q_surface = Q_met + Q_art, so the net arterial reservoir heat is
F_art = Q_surface - Q_met (storage ~ 0). Reports E_surface, E_met, E_art in
Mcal/day and the metabolic-closure ratio eta = Q_met/Q_surface, per species and
water temperature (active mode). Reads existing multicase_comparison_data.json;
no new simulations required.

Outputs:
  paper/generated/energy_partition.csv        (all species, all temps)
  paper/generated/energy_partition_table.tex  (appendix LaTeX table, -2/10/30 C)
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "results"
OUT = ROOT / "paper" / "generated"
OUT.mkdir(exist_ok=True)

W_PER_MCAL_DAY = 4.184e6 / 86400.0  # 48.4 W per Mcal/day

# comparative species order + minke; label + directory
SPECIES = [
    ("Humpback", "humpback"), ("Right whale", "right_whale"),
    ("Blue whale", "blue_whale"), ("Bowhead", "bowhead"),
    ("Fin whale", "fin_whale"), ("Gray whale", "gray_whale"),
    ("Sei whale", "sei_whale"), ("Minke$^{\\dagger}$", "minke"),
]
TEMPS_TABLE = [-2.0, 10.0, 30.0]


def load_cases(sp_dir):
    f = RES / sp_dir / "multicase_comparison_data.json"
    if not f.exists():
        return []
    d = json.load(open(f))
    cases = d.get("cases") if isinstance(d, dict) else d
    return cases or []


def w_to_mcal(w):
    return w * 86400.0 / 4.184e6


rows = []            # full csv
table_rows = {}      # (label) -> {temp: dict}
for label, sp in SPECIES:
    cases = load_cases(sp)
    table_rows[label] = {}
    for c in cases:
        if c.get("mode") != "active":
            continue
        # baseline FA=1, BCI=1 only
        if abs(c.get("food_availability", 1.0) - 1.0) > 1e-6:
            continue
        if abs(c.get("body_condition_index", 1.0) - 1.0) > 1e-6:
            continue
        bm = c.get("biomarkers", {})
        qmet = bm.get("Q_met_W")
        qloss = bm.get("Q_loss_W")
        if qmet is None or qloss is None:
            continue
        tw = c.get("T_water_C")
        fart = qloss - qmet
        eta = qmet / qloss if qloss else float("nan")
        rec = dict(species=label, sp=sp, T_water_C=tw,
                   Q_met_W=qmet, Q_surface_W=qloss, F_art_W=fart,
                   E_met_Mcal=w_to_mcal(qmet), E_surface_Mcal=w_to_mcal(qloss),
                   E_art_Mcal=w_to_mcal(fart), eta=eta,
                   core_temp_C=c.get("core_temp_C"))
        rows.append(rec)
        table_rows[label][round(tw)] = rec

# ---- CSV ----
import csv
cols = ["species", "sp", "T_water_C", "Q_met_W", "Q_surface_W", "F_art_W",
        "E_met_Mcal", "E_surface_Mcal", "E_art_Mcal", "eta", "core_temp_C"]
with open(OUT / "energy_partition.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=cols)
    w.writeheader()
    for r in sorted(rows, key=lambda x: (x["sp"], x["T_water_C"])):
        w.writerow(r)

# ---- LaTeX table (appendix) ----
lines = []
lines.append("% Auto-generated by scripts/postprocessing/build_energy_partition.py")
lines.append("\\begin{table*}[!ht]")
lines.append("\\centering")
lines.append("\\caption{Whole-domain steady-state energy partition (active mode, "
             "well-fed baseline). $E_\\mathrm{surface}$ is the surface heat-loss "
             "equivalent, $E_\\mathrm{met}$ the prescribed metabolic heat, and "
             "$E_\\mathrm{art}=E_\\mathrm{surface}-E_\\mathrm{met}$ the net heat "
             "supplied by the defended arterial reservoir; $\\eta=Q_\\mathrm{met}/"
             "Q_\\mathrm{surface}$ is the metabolic-closure ratio. All energies in "
             "Mcal\\,day$^{-1}$. The arterial reservoir supplies the majority of "
             "surface heat loss, and $\\eta$ tracks blubber insulation.}")
lines.append("\\label{tab:energy_partition}")
lines.append("\\small")
lines.append("\\begin{tabular}{@{}l" + "rrrr" * len(TEMPS_TABLE) + "@{}}")
lines.append("\\toprule")
hdr = "Species"
for t in TEMPS_TABLE:
    hdr += " & \\multicolumn{4}{c}{$T_w=%d^{\\circ}$C}" % t
lines.append(hdr + " \\\\")
sub = ""
for _ in TEMPS_TABLE:
    sub += " & $E_\\mathrm{met}$ & $E_\\mathrm{art}$ & $E_\\mathrm{surf}$ & $\\eta$"
lines.append(sub + " \\\\")
lines.append("\\midrule")
for label, sp in SPECIES:
    tr = table_rows.get(label, {})
    if not tr:
        continue
    row = label
    for t in TEMPS_TABLE:
        r = tr.get(t)
        if r is None:
            row += " & {--} & {--} & {--} & {--}"
        else:
            row += " & %.0f & %.0f & %.0f & %.2f" % (
                r["E_met_Mcal"], r["E_art_Mcal"], r["E_surface_Mcal"], r["eta"])
    lines.append(row + " \\\\")
lines.append("\\bottomrule")
lines.append("\\end{tabular}")
lines.append("\\end{table*}")
(OUT / "energy_partition_table.tex").write_text("\n".join(lines) + "\n")

# ---- console summary ----
print(f"{len(rows)} (species,temp) records written")
print("\nHeadline check (active, -2 C):")
print(f"{'species':12s} {'E_met':>8s} {'E_art':>8s} {'E_surf':>8s} {'eta':>5s}")
for label, sp in SPECIES:
    r = table_rows.get(label, {}).get(-2)
    if r:
        print(f"{label:12s} {r['E_met_Mcal']:8.0f} {r['E_art_Mcal']:8.0f} "
              f"{r['E_surface_Mcal']:8.0f} {r['eta']:5.2f}")
print(f"\nWrote {OUT/'energy_partition.csv'}")
print(f"Wrote {OUT/'energy_partition_table.tex'}")
