#!/usr/bin/env python3
"""Generate two appendix tables from the species YAML configs:
  1. paper/generated/ttn_table.tex   (tab:ttn) - per-species set-point, thermoneutral
     anchor, FMR and its literature source.
  2. paper/generated/provenance_table.tex (tab:provenance) - parameter master table
     (symbol, meaning, unit, value/range, source, measured/assumed, transformation).
No simulations required; reads data/species/*.yaml and data/<sp>/materials.json.
"""
import yaml, json, glob, os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "paper" / "generated"
OUT.mkdir(exist_ok=True)

ORDER = ["humpback", "right_whale", "blue_whale", "bowhead",
         "fin_whale", "gray_whale", "sei_whale", "minke"]
LABEL = {"humpback": "Humpback", "right_whale": "Right whale", "blue_whale": "Blue whale",
         "bowhead": "Bowhead", "fin_whale": "Fin whale", "gray_whale": "Gray whale",
         "sei_whale": "Sei whale", "minke": "Minke$^{\\dagger}$"}


def short_source(s):
    s = s or ""
    for key, tag in [("Blawas", "Blawas et al. (2025)"), ("Fortune", "Fortune et al. (2013)"),
                     ("Folkow", "Folkow \\& Blix (1992)"), ("George", "George (2009)"),
                     ("Kleiber", "0.5$\\times$Kleiber BMR")]:
        if key in s:
            return tag
    return s[:38]


def load(sp):
    d = yaml.safe_load(open(ROOT / "data" / "species" / f"{sp}.yaml"))
    return d


# ---------- Table 1: Ttn / setpoint / FMR provenance ----------
rows = []
for sp in ORDER:
    d = load(sp)
    rows.append((LABEL[sp], d.get("core_temperature_C"), d.get("thermoneutral_water_C"),
                 d.get("fmr_watts"), short_source(d.get("fmr_source", ""))))

t1 = ["% Auto-generated by build_provenance_tables.py",
      "\\begin{table*}[!ht]", "\\centering",
      "\\caption{Species set-points and metabolic provenance. $T_a$ is the prescribed "
      "arterial/core set-point; $T_\\mathrm{tn}$ the thermoneutral anchor of the control "
      "law (bandwidth $\\lambda=\\SI{5}{\\degreeCelsius}$ for all "
      "species); FMR is the field metabolic rate driving the volumetric metabolic source. "
      "The control law operates in its heat-retention branch across the tested range, so no "
      "species enters sustained net vasodilation (a structural assumption).}",
      "\\label{tab:ttn}", "\\small",
      "\\begin{tabular}{@{}lS[table-format=2.1]S[table-format=2.1]S[table-format=5.0]l@{}}",
      "\\toprule",
      "Species & {$T_a$ (\\si{\\degreeCelsius})} & {$T_\\mathrm{tn}$ (\\si{\\degreeCelsius})} "
      "& {FMR (\\si{\\watt})} & {FMR source} \\\\", "\\midrule"]
for lab, ta, ttn, fmr, src in rows:
    t1.append(f"{lab} & {ta} & {ttn} & {fmr:.0f} & {src} \\\\")
t1 += ["\\bottomrule", "\\end{tabular}",
       "\\smallskip\\\\ \\footnotesize $^{\\dagger}$Minke calibration proxy.",
       "\\end{table*}"]
(OUT / "ttn_table.tex").write_text("\n".join(t1) + "\n")

# ---------- Table 2: parameter provenance master ----------
# Rows verified from configs/materials/manuscript. Ranges span the 8 species.
prov = [
    ("$M$", "Body mass", "\\si{\\kilo\\gram}", "7\\,000--100\\,000", "Species literature", "measured", "geometry scaling"),
    ("$T_a$", "Arterial/core set-point", "\\si{\\degreeCelsius}", "33.8--36.1", "Species literature", "assumed (fixed)", "---"),
    ("$T_\\mathrm{tn}$", "Thermoneutral anchor", "\\si{\\degreeCelsius}", "0--25", "Calibrated", "assumed", "control law"),
    ("$\\lambda$", "Control bandwidth", "\\si{\\degreeCelsius}", "5.0", "Assumed", "assumed", "---"),
    ("$k_\\mathrm{blub}$", "Blubber conductivity", "\\si{\\watt\\per\\m\\per\\kelvin}", "0.19--0.25", "Kvadsheim et al.\\ (1996); Dunkin et al.\\ (2005)", "measured", "effective, $/\\mathrm{BCI}$"),
    ("$k_\\mathrm{core}$", "Core conductivity", "\\si{\\watt\\per\\m\\per\\kelvin}", "0.56", "Bowman et al.\\ (1975)", "measured", "---"),
    ("$\\omega_{b,\\mathrm{core}}$", "Core blood perfusion", "\\si{\\kg\\per\\m\\cubed\\per\\s}", "0.80", "Mammalian range (Wang et al.\\ 2010)", "assumed", "mass-perfusion"),
    ("$\\omega_{b,\\mathrm{blub}}$", "Nominal blubber perfusion", "\\si{\\kg\\per\\m\\cubed\\per\\s}", "0.08", "Reduced (Scholander et al.\\ 1955)", "assumed", "$\\times f_\\mathrm{perf}$ under control"),
    ("$f_\\mathrm{perf}$", "CCHE reduction factor", "---", "0.012", "Calibrated (minke)", "assumed", "active-control scaling"),
    ("$Q_\\mathrm{met}$", "Volumetric metabolic heat", "\\si{\\watt\\per\\m\\cubed}", "per species", "FMR (see Table~\\ref{tab:ttn})", "measured/est.", "FMR-forward scaling"),
    ("$h$", "Effective external conductance", "\\si{\\watt\\per\\m\\squared\\per\\kelvin}", "35--60", "Effective (calibrated)", "assumed", "$\\times$ swim multiplier"),
    ("$\\varepsilon_\\mathrm{rete}$", "CCHE effectiveness", "---", "per region", "Assumed", "assumed", "control law"),
    ("$\\mathrm{BCI}$", "Body-condition index", "---", "0.6--1.0", "Scenario", "assumed", "$k^\\mathrm{eff}_\\mathrm{blub}=k_\\mathrm{blub}/\\mathrm{BCI}$"),
    ("$\\mathrm{FA}$", "Food availability", "---", "0.3--1.0", "Scenario", "assumed", "$\\dot Q_\\mathrm{met}\\times\\mathrm{FA}$"),
]
t2 = ["% Auto-generated by build_provenance_tables.py",
      "\\begin{table*}[!ht]", "\\centering",
      "\\caption{Master parameter provenance. Values span the eight modelled species; "
      "species-specific values are in the configuration files of the supplementary repository. "
      "``Transformation'' gives the rule mapping the baseline value to the value used in a run.}",
      "\\label{tab:provenance}", "\\small",
      "\\begin{tabular}{@{}llllll l@{}}", "\\toprule",
      "Symbol & Meaning & Unit & Value/range & Source & M/A & Transformation \\\\", "\\midrule"]
for sym, mean, unit, val, src, ma, trans in prov:
    t2.append(f"{sym} & {mean} & {unit} & {val} & {src} & {ma} & {trans} \\\\")
t2 += ["\\bottomrule", "\\end{tabular}",
       "\\smallskip\\\\ \\footnotesize M/A: measured or assumed. CCHE: counter-current heat exchange.",
       "\\end{table*}"]
(OUT / "provenance_table.tex").write_text("\n".join(t2) + "\n")

print("Wrote ttn_table.tex and provenance_table.tex")
for lab, ta, ttn, fmr, src in rows:
    print(f"  {lab:16s} Ta={ta} Ttn={ttn} FMR={fmr}W  {src}")
